// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: Cutter_countB

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Main
void ui_Main_screen_init(void);
lv_obj_t * ui_Main;
lv_obj_t * ui_Panel9;
lv_obj_t * ui_Panel11;
lv_obj_t * ui_Label13;
lv_obj_t * ui_Image2;
lv_obj_t * ui_Panel12;
lv_obj_t * ui_CPM;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_CPMtimePanel;
lv_obj_t * ui_CPMtime;
lv_obj_t * ui_LedCPMtime;
lv_obj_t * ui_CPMtimeLabel;
lv_obj_t * ui_Panel4;
lv_obj_t * ui_CPMcountPanel;
lv_obj_t * ui_CPMcount;
lv_obj_t * ui_LedCPMcount;
lv_obj_t * ui_CPMcountLabel;
lv_obj_t * ui_Label5;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_home_[1] = {&ui_img_home_22_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Main_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Main);
}
