// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_t_

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
lv_obj_t * ui_Screen2;
lv_obj_t * ui_Panelscreen2;
lv_obj_t * ui_Panel8;
lv_obj_t * ui_Label7;
void ui_event_Button1(lv_event_t * e);
lv_obj_t * ui_Button1;
lv_obj_t * ui_Image2;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_Buttonauto;
lv_obj_t * ui_Label6;
lv_obj_t * ui_Panel4;
lv_obj_t * ui_Panel5;
lv_obj_t * ui_Panelsettime1;
lv_obj_t * ui_Labelsettime1;
lv_obj_t * ui_Panelsettime2;
lv_obj_t * ui_Labelsettime2;
lv_obj_t * ui_Panelsetauto;
lv_obj_t * ui_Labelautotune;
lv_obj_t * ui_Label11;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Panelkeyboad;
lv_obj_t * ui_TextAreakey;
lv_obj_t * ui_Keyboard;


// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
lv_obj_t * ui_Screen3;
lv_obj_t * ui_Panel9;
lv_obj_t * ui_Panel11;
void ui_event_Button4(lv_event_t * e);
lv_obj_t * ui_Button4;
lv_obj_t * ui_Image3;
lv_obj_t * ui_Label13;
lv_obj_t * ui_Panel12;
lv_obj_t * ui_Labelcurrenttime;
lv_obj_t * ui_Label4;
lv_obj_t * ui_Image1;
lv_obj_t * ui_Panelspeedrpm;
lv_obj_t * ui_Labelspeedrpm;
lv_obj_t * ui_Label2;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_home_[1] = {&ui_img_home_22_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen3_screen_init);
    }
}
void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen2_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen2_screen_init();
    ui_Screen3_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen2);
}
