// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: Cutter_countB

#ifndef _CUTTER_COUNTB_UI_H
#define _CUTTER_COUNTB_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Main
void ui_Main_screen_init(void);
extern lv_obj_t * ui_Main;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_Panel11;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Panel12;
extern lv_obj_t * ui_CPM;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_home_22_png);    // assets/home 22.png



LV_FONT_DECLARE(ui_font_Font1);
LV_FONT_DECLARE(ui_font_Font2);
LV_FONT_DECLARE(ui_font_font350);
LV_FONT_DECLARE(ui_font_font360);
LV_FONT_DECLARE(ui_font_font500);
LV_FONT_DECLARE(ui_font_Fontth100);
LV_FONT_DECLARE(ui_font_Fontth35);


void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
