// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Cutter_count

#ifndef _CUTTER_COUNT_UI_H
#define _CUTTER_COUNT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Main
void ui_Main_screen_init(void);
extern lv_obj_t * ui_Main;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_Panel11;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Panel12;
extern lv_obj_t * ui_CPM1;
extern lv_obj_t * ui_CPM2;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_CPMtimePanel;
extern lv_obj_t * ui_CPMtime;
extern lv_obj_t * ui_LedCPMtime;
extern lv_obj_t * ui_CPMtimeLabel;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_CPMcountPanel;
extern lv_obj_t * ui_CPMcount;
extern lv_obj_t * ui_LedCPMcount;
extern lv_obj_t * ui_CPMcountLabel;
extern lv_obj_t * ui_Label5;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_1989276256);    // assets/search-engine-optimization.png
LV_IMG_DECLARE(ui_img_home_22_png);    // assets/home 22.png

// FONTS
LV_FONT_DECLARE(ui_font_CPM300);
LV_FONT_DECLARE(ui_font_Kanit35);
LV_FONT_DECLARE(ui_font_NotoSansTH60Bold);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
