// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_t_

#include "../ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0x4E4A4A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panelscreen2 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Panelscreen2, 785);
    lv_obj_set_height(ui_Panelscreen2, 462);
    lv_obj_set_x(ui_Panelscreen2, 1);
    lv_obj_set_y(ui_Panelscreen2, 0);
    lv_obj_set_align(ui_Panelscreen2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panelscreen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panelscreen2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panelscreen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel8 = lv_obj_create(ui_Panelscreen2);
    lv_obj_set_width(ui_Panel8, 780);
    lv_obj_set_height(ui_Panel8, 71);
    lv_obj_set_x(ui_Panel8, 0);
    lv_obj_set_y(ui_Panel8, -195);
    lv_obj_set_align(ui_Panel8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel8, lv_color_hex(0x1D6AE4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Panel8);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "SETTING");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &ui_font_Font2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1 = lv_btn_create(ui_Panel8);
    lv_obj_set_width(ui_Button1, 150);
    lv_obj_set_height(ui_Button1, 150);
    lv_obj_set_x(ui_Button1, 334);
    lv_obj_set_y(ui_Button1, 0);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0x1D6AE4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_Button1);
    lv_img_set_src(ui_Image2, &ui_img_home_22_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 512
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 512
    lv_obj_set_x(ui_Image2, 4);
    lv_obj_set_y(ui_Image2, 0);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image2, 20);

    ui_Panel2 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Panel2, 763);
    lv_obj_set_height(ui_Panel2, 365);
    lv_obj_set_x(ui_Panel2, 2);
    lv_obj_set_y(ui_Panel2, 32);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_outline_color(ui_Panel2, lv_color_hex(0xB97C26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Panel2, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Panel2, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_Panel2);
    lv_obj_set_width(ui_Panel3, 128);
    lv_obj_set_height(ui_Panel3, 119);
    lv_obj_set_x(ui_Panel3, -272);
    lv_obj_set_y(ui_Panel3, -71);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel3, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x6B6969), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Panel3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Panel3, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Buttonauto = lv_btn_create(ui_Panel3);
    lv_obj_set_width(ui_Buttonauto, 105);
    lv_obj_set_height(ui_Buttonauto, 97);
    lv_obj_set_align(ui_Buttonauto, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Buttonauto, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Buttonauto, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Buttonauto, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Buttonauto, lv_color_hex(0x13480E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Buttonauto, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Buttonauto, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Buttonauto, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Buttonauto, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Buttonauto, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Buttonauto);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "AUTO");
    lv_obj_set_style_text_font(ui_Label6, &ui_font_Fontth35, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_Panel2);
    lv_obj_set_width(ui_Panel4, 502);
    lv_obj_set_height(ui_Panel4, 310);
    lv_obj_set_x(ui_Panel4, 122);
    lv_obj_set_y(ui_Panel4, 20);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Panel4, lv_color_hex(0xB97C26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Panel4, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel5 = lv_obj_create(ui_Panel4);
    lv_obj_set_width(ui_Panel5, 7);
    lv_obj_set_height(ui_Panel5, 301);
    lv_obj_set_x(ui_Panel5, 2);
    lv_obj_set_y(ui_Panel5, 1);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0xB97C26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panelsettime1 = lv_obj_create(ui_Panel4);
    lv_obj_set_width(ui_Panelsettime1, 224);
    lv_obj_set_height(ui_Panelsettime1, 290);
    lv_obj_set_x(ui_Panelsettime1, -122);
    lv_obj_set_y(ui_Panelsettime1, 5);
    lv_obj_set_align(ui_Panelsettime1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panelsettime1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panelsettime1, lv_color_hex(0x3E3939), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panelsettime1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelsettime1 = lv_label_create(ui_Panelsettime1);
    lv_obj_set_width(ui_Labelsettime1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelsettime1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelsettime1, 3);
    lv_obj_set_y(ui_Labelsettime1, 0);
    lv_obj_set_align(ui_Labelsettime1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelsettime1, "18");
    lv_obj_set_style_text_color(ui_Labelsettime1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labelsettime1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labelsettime1, &ui_font_Fontth100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panelsettime2 = lv_obj_create(ui_Panel4);
    lv_obj_set_width(ui_Panelsettime2, 224);
    lv_obj_set_height(ui_Panelsettime2, 290);
    lv_obj_set_x(ui_Panelsettime2, 131);
    lv_obj_set_y(ui_Panelsettime2, 5);
    lv_obj_set_align(ui_Panelsettime2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panelsettime2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panelsettime2, lv_color_hex(0x3E3939), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panelsettime2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelsettime2 = lv_label_create(ui_Panelsettime2);
    lv_obj_set_width(ui_Labelsettime2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelsettime2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Labelsettime2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelsettime2, "27");
    lv_obj_set_style_text_color(ui_Labelsettime2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labelsettime2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labelsettime2, &ui_font_Fontth100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panelsetauto = lv_obj_create(ui_Panel2);
    lv_obj_set_width(ui_Panelsetauto, 174);
    lv_obj_set_height(ui_Panelsetauto, 73);
    lv_obj_set_x(ui_Panelsetauto, -272);
    lv_obj_set_y(ui_Panelsetauto, 102);
    lv_obj_set_align(ui_Panelsetauto, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panelsetauto, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_outline_color(ui_Panelsetauto, lv_color_hex(0x5D5C57), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Panelsetauto, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Panelsetauto, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Panelsetauto, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelautotune = lv_label_create(ui_Panelsetauto);
    lv_obj_set_width(ui_Labelautotune, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelautotune, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Labelautotune, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelautotune, "20");
    lv_obj_set_style_text_color(ui_Labelautotune, lv_color_hex(0x524E4E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labelautotune, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labelautotune, &ui_font_Font2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, -275);
    lv_obj_set_y(ui_Label11, 37);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "AUTO TUNE");
    lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0x494444), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label11, &ui_font_Fontth35, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 254);
    lv_obj_set_y(ui_Label5, -107);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "จำนวนตัด/นาที");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0x4B4B4B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &ui_font_Fontth35, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 6);
    lv_obj_set_y(ui_Label3, -107);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "รอบ/นาที");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0x4B4B4B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &ui_font_Fontth35, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panelkeyboad = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Panelkeyboad, 785);
    lv_obj_set_height(ui_Panelkeyboad, 415);
    lv_obj_set_x(ui_Panelkeyboad, 0);
    lv_obj_set_y(ui_Panelkeyboad, 25);
    lv_obj_set_align(ui_Panelkeyboad, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Panelkeyboad, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Panelkeyboad, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panelkeyboad, lv_color_hex(0x4F4E4E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panelkeyboad, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextAreakey = lv_textarea_create(ui_Panelkeyboad);
    lv_obj_set_width(ui_TextAreakey, 761);
    lv_obj_set_height(ui_TextAreakey, LV_SIZE_CONTENT);    /// 63
    lv_obj_set_x(ui_TextAreakey, 0);
    lv_obj_set_y(ui_TextAreakey, -165);
    lv_obj_set_align(ui_TextAreakey, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_TextAreakey, 5);
    lv_textarea_set_placeholder_text(ui_TextAreakey, "กดจำนวนที่ต้องการ....");
    lv_textarea_set_one_line(ui_TextAreakey, true);
    lv_obj_set_style_text_color(ui_TextAreakey, lv_color_hex(0x383737), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextAreakey, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextAreakey, &ui_font_Fontth35, LV_PART_MAIN | LV_STATE_DEFAULT);


    lv_obj_set_style_text_font(ui_TextAreakey, &ui_font_Fontth35, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);

    ui_Keyboard = lv_keyboard_create(ui_Panelkeyboad);
    lv_keyboard_set_mode(ui_Keyboard, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_Keyboard, 784);
    lv_obj_set_height(ui_Keyboard, 335);
    lv_obj_set_x(ui_Keyboard, 0);
    lv_obj_set_y(ui_Keyboard, 36);
    lv_obj_set_align(ui_Keyboard, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Keyboard, lv_color_hex(0x4F4E4E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Keyboard, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Keyboard, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Keyboard, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(ui_Keyboard, lv_color_hex(0x000000), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Keyboard, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Keyboard, 2, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Keyboard, LV_BORDER_SIDE_FULL, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Keyboard, 2, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Keyboard, 0, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Keyboard, LV_TEXT_ALIGN_AUTO, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Keyboard, &lv_font_montserrat_36, LV_PART_ITEMS | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Keyboard, ui_TextAreakey);

}
