// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_t_

#include "../ui.h"

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen3, lv_color_hex(0x4E4A4A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel9 = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_Panel9, 785);
    lv_obj_set_height(ui_Panel9, 462);
    lv_obj_set_x(ui_Panel9, 0);
    lv_obj_set_y(ui_Panel9, -1);
    lv_obj_set_align(ui_Panel9, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel11 = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_Panel11, 780);
    lv_obj_set_height(ui_Panel11, 71);
    lv_obj_set_x(ui_Panel11, 0);
    lv_obj_set_y(ui_Panel11, -195);
    lv_obj_set_align(ui_Panel11, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel11, lv_color_hex(0x1D6AE4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel11, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel11, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button4 = lv_btn_create(ui_Panel11);
    lv_obj_set_width(ui_Button4, 150);
    lv_obj_set_height(ui_Button4, 150);
    lv_obj_set_x(ui_Button4, 334);
    lv_obj_set_y(ui_Button4, 0);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0x1D6AE4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image3 = lv_img_create(ui_Button4);
    lv_img_set_src(ui_Image3, &ui_img_1329202414);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 128
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 128
    lv_obj_set_x(ui_Image3, 4);
    lv_obj_set_y(ui_Image3, 0);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image3, 100);

    ui_Label13 = lv_label_create(ui_Panel11);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "จำนวนตัด/นาที");
    lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label13, &ui_font_Font2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel12 = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_Panel12, 763);
    lv_obj_set_height(ui_Panel12, 365);
    lv_obj_set_x(ui_Panel12, 1);
    lv_obj_set_y(ui_Panel12, 31);
    lv_obj_set_align(ui_Panel12, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Panel12, lv_color_hex(0xB97C26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Panel12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Panel12, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Panel12, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelcurrenttime = lv_label_create(ui_Panel12);
    lv_obj_set_width(ui_Labelcurrenttime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelcurrenttime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelcurrenttime, -65);
    lv_obj_set_y(ui_Labelcurrenttime, 4);
    lv_obj_set_align(ui_Labelcurrenttime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelcurrenttime, "55");
    lv_obj_set_style_text_color(ui_Labelcurrenttime, lv_color_hex(0x2F2D2D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labelcurrenttime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labelcurrenttime, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Panel12);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 304);
    lv_obj_set_y(ui_Label4, 61);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "speed");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0x564F4F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_Panel12);
    lv_img_set_src(ui_Image1, &ui_img_performance_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 512
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 512
    lv_obj_set_x(ui_Image1, 301);
    lv_obj_set_y(ui_Image1, -22);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image1, 70);

    ui_Panelspeedrpm = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_Panelspeedrpm, 137);
    lv_obj_set_height(ui_Panelspeedrpm, 66);
    lv_obj_set_x(ui_Panelspeedrpm, 303);
    lv_obj_set_y(ui_Panelspeedrpm, 158);
    lv_obj_set_align(ui_Panelspeedrpm, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panelspeedrpm, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_outline_color(ui_Panelspeedrpm, lv_color_hex(0xB97C26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Panelspeedrpm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Panelspeedrpm, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Panelspeedrpm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelspeedrpm = lv_label_create(ui_Panelspeedrpm);
    lv_obj_set_width(ui_Labelspeedrpm, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelspeedrpm, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelspeedrpm, -24);
    lv_obj_set_y(ui_Labelspeedrpm, 2);
    lv_obj_set_align(ui_Labelspeedrpm, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelspeedrpm, "20");
    lv_obj_set_style_text_color(ui_Labelspeedrpm, lv_color_hex(0x564F4F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labelspeedrpm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labelspeedrpm, &ui_font_Font2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Panelspeedrpm);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 40);
    lv_obj_set_y(ui_Label2, 13);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "RPM");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x564F4F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);

}
